###### /******************** SENDING ERROR MESSAGES IN RESPONSE ********************/
#  server.error.include-message=always
##### /******************** LOGGING ********************/
#logging:
#  config: classpath:logback-dev.xml
#  level:
#    ##### /----- START LOGGING FROM INFO LEVEL -----/
#    root: INFO
#    ##### /----- LOGGING SECURITY FILTERS IN CONSOLE -----/
#    org.springframework.security: trace

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  ##### /----- EXECUTES CODE IN data.sql AFTER SCHEMA CREATION -----/
  sql:
    init:
      mode: always

  ##### /----- MAKE LOGGING COLORFUL -----/
  output:
    ansi:
      enabled: ALWAYS

  devtools:
    livereload:
      enabled: true
#      restart:
#        poll-interval: 500ms
#        quiet-period: 100ms
#        exclude: "**/uploads/**"




##### /----- JWT VARIABLES -----/
JWT:
  secret: 5e1ff336e89089ebec6e882bb8bd3330c3360c6206db88b20c17c4e1a85ee52b
  expirationMS: 3600000