name: Build and deploy image to dockerhub

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy image to docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

#      - name: Unit Tests
#        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -b package --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker Image and push to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-product-be:latest
